# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=200)),
                ('recommend', models.CharField(max_length=200)),
                ('number_of_reviews', models.CharField(max_length=200)),
            ],
        ),
    ]
