# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.Reviews'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='number_of_reviews',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='recommend',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
